version: "2.4"
services:
  gcloud-sdk:
    image: google/cloud-sdk:latest
    ports:
      - 8085:8085
    command: gcloud beta emulators pubsub start --project=pulsar-io-google-pubsub --host-port=0.0.0.0:8085

  pulsar-io-google-pubsub-test:
    container_name: pulsar-io-google-pubsub-test
    build:
      context: ../../
      dockerfile: .ci/integrations/Dockerfile
    environment:
      - PUBSUB_EMULATOR_HOST=gcloud:8085
    ports:
      - 8080:8080
      - 6650:6650
    links:
      - gcloud-sdk:gcloud

